title: Linh Anh Le (Celia)
logo: "/profile(1).jpg" 

description: > 
    Call me Linh Anh or Celia. 
    <br><br>
    I am a data analyst with more than four years working in the nonprofit sector and public policy. Upon completing the Bachelor's degree in Quant. Economics and Education, I have accumulated diverse experience in regression analysis, VBA automation, data visualization, and web scraping. 
    <br><br>
    Currently working my way up to a data scientist role!
    <br><br>
    <a href = "https://www.linkedin.com/in/linh-anh-le-524b6814b/">View My LinkedIn Profile</a>
    <br>
    <a href = "https://drive.google.com/file/d/1JY0vDX4esI3t28CmCk7OxcnuxR5Ymzsq/view?usp=sharing/">View My Resume</a>
theme: pages-themes/minimal@v0.2.0
