title: Linh Anh Le (Celia)
logo: "/profile(1).jpg" 

description: Call me Linh Anh or Celia. I am a data analyst with more than four years working in the nonprofit sector and public policy. 
Upon completing in Bachelor's degree in Quant. Economics and Education, I have accumulated diverse experience in regression analysis, VBA automation, data visualization, and web scraping. 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
