title: Linh Anh Le
logo: /profile(1).jpg
description: I am a data analyst with more than four years working in the nonprofit sector and public policy. Upon completing the Bachelor's degree in Quant. Economics and Education, I have accumulated diverse experience in regression analysis, VBA automation, data visualization, and web scraping. Currently working my way up to a data scientist role!
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
